import SectionHeader from "./ui/SectionHeader";

function KeyFeatures() {
  const features = [
    {
      title: "GitHub Integration",
      desc: "Import your project directly from GitHub using APIs. No setup needed.",
      video: "/videos/github-integration.mp4",
    },
    {
      title: "Live Code Editing",
      desc: "Edit backend code directly from the browser in a VSCode-like interface.",
      video: "/videos/live-code-editing.mp4",
    },
    {
      title: "AI-Powered Node Flows",
      desc: "Paste your fetch chains or backend logic and get a visual node-based representation auto-generated by AI.",
      video: "/videos/ai-node-flows.mp4",
    },
    {
      title: "Frontend + Backend State Sync",
      desc: "Connect your local frontend and backend apps and see real-time state, props, and backend responses.",
      video: "/videos/state-sync.mp4",
    },
    {
      title: "Smart Test Simulation",
      desc: "Simulate user flows like login/signup using actual frontend state—no more hardcoding payloads.",
      video: "/videos/test-simulation.mp4",
    },
    {
      title: "Flow Break Detection",
      desc: "Instantly spot where the request breaks and get actionable fix suggestions.",
      video: "/videos/flow-break-detection.mp4",
    },
    {
      title: "Live Route Visualization",
      desc: "Discover all your backend routes and map them visually with connection flows.",
      video: "/videos/route-visualization.mp4",
    },
    {
      title: "One-click Test Generation",
      desc: "AI creates tests based on actual user interactions and edge cases.",
      video: "/videos/test-generation.mp4",
    },
    {
      title: "Drag-and-Drop Debugging",
      desc: "Build flows and test them visually using an infinite canvas node-based system.",
      video: "/videos/drag-drop-debugging.mp4",
    },
  ];

  return (
    <section className="px-6 py-24 max-w-6xl mx-auto">
      <SectionHeader
        title="Key Features"
        description="Revolutionary tools that transform how you debug and develop"
      />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {features.map((feature, i) => (
          <div
            key={i}
            style={{
              position: "relative",
              width: "100%",
              aspectRatio: "16/9",
              borderRadius: "1.5rem",
              overflow: "hidden",
              background: "rgba(20, 20, 20, 0.8)",
              border: "1px solid rgba(255, 204, 0, 0.2)",
              transition: "all 0.3s ease",
              cursor: "pointer",
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.transform = "scale(1.02)";
              e.currentTarget.style.boxShadow =
                "0 20px 40px rgba(255, 204, 0, 0.3)";
              e.currentTarget.style.borderColor = "rgba(255, 204, 0, 0.4)";
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.transform = "scale(1)";
              e.currentTarget.style.boxShadow = "none";
              e.currentTarget.style.borderColor = "rgba(255, 204, 0, 0.2)";
            }}
          >
            {/* Video Background */}
            {/* {feature.video ? (
              <video
                autoPlay
                loop
                muted
                playsInline
                style={{
                  position: "absolute",
                  top: 0,
                  left: 0,
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                  opacity: 0.8,
                }}
              >
                <source src={feature.video} type="video/mp4" />
              </video>
            ) : ( */}

            <div
              className="absolute top-0 left-0 w-full h-full flex justify-center items-center text-[#FFC107] text-[16px] font-bold"
              style={{
                background: "rgba(30,30,30,0.7)",
              }}
            >
              Videos coming soon....
            </div>
            {/* )} */}
            {/* Gradient Overlay */}
            <div
              style={{
                position: "absolute",
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                background:
                  "linear-gradient(transparent 40%, rgba(20, 20, 20, 0.3) 60%, rgba(20, 20, 20, 0.9) 100%)",
                zIndex: 1,
              }}
            />
            {/* Text Content */}
            <div
              style={{
                position: "absolute",
                bottom: "2rem",
                left: "2rem",
                right: "2rem",
                zIndex: 2,
              }}
            >
              <h3
                style={{
                  fontSize: "1.5rem",
                  fontWeight: "bold",
                  color: "#FFC107",
                  marginBottom: "0.75rem",
                  textShadow:
                    "0 4px 8px rgba(0, 0, 0, 0.8), 0 2px 4px rgba(0, 0, 0, 0.6)",
                  lineHeight: "1.2",
                }}
              >
                {feature.title}
              </h3>
              <p
                style={{
                  color: "#E5E7EB",
                  fontSize: "0.875rem",
                  lineHeight: "1.5",
                  textShadow:
                    "0 2px 4px rgba(0, 0, 0, 0.8), 0 1px 2px rgba(0, 0, 0, 0.6)",
                  opacity: 0.95,
                }}
              >
                {feature.desc}
              </p>
            </div>
            {/* Grain Texture Overlay */}
            <div
              style={{
                position: "absolute",
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                backgroundImage: `radial-gradient(
                  circle at 1px 1px,
                  rgba(255, 255, 255, 0.2) 1px,
                  transparent 0
                )`,
                backgroundSize: "20px 20px",
                opacity: 0.3,
                pointerEvents: "none",
                zIndex: 3,
              }}
            />
          </div>
        ))}
      </div>
    </section>
  );
}

export default KeyFeatures;
